### ISSUE TITLE
Make the maintenance list page responsive

### ISSUE THREAD

**Issue by nikneem** [nikneem/shortlink-frontend#7]
The list page is now not responsive. It must be responsive so it's easy to use on all devices.

This means that the panel must scale and columns should be hidden when there's not enough space.

- Make the card scale
- Make the endpoint column single line and show ellipsis when needed
  - Show full endpoint in a tooltip
- Hide the expiration column when not enough space

**Comment by amaan-ahmad** [comment]
Hey, @nikneem I am interested in working on it. Kindly assign it to me. 
Thanks

**Comment by nikneem** [comment]
Thanks! If you need any help, please reach out!

**Comment by nikneem** [comment]
Hi, do you have any progress on this one?
